### ISSUE TITLE
Android support ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [hdsdi3g/MyDMAM#148]
Thanks for your awesome work :)

**Comment by hdsdi3g** [comment]
Thank for your message !
MyDMAM use Bootstrap (the 2.x old and original version), and should be fully functional with Android browsers.
Now, I don't think so you can run it with Dalvik, and check this is not in my TODO list, actually !

**Comment by LifeIsStrange** [comment]
xD I accidentally broke the screen of my oneplus so since today it's not a priority for me... 
Thanks again !
