### ISSUE TITLE
ant build

### ISSUE THREAD

**Issue by pyronico** [hdsdi3g/MyDMAM#290]
Après avoir cloné le repo, la commande ant build échoue.

Pour pouvoir compiler le projet, j'ai du effectuer les modifs suivantes:

* Renommer une variable dans /conf/tools/ant-utils.xml :
${mydmam.websiteurldownload} --> ${mydmam.website.url.download}

* Puis créer le répertoire /app/models

**Comment by hdsdi3g** [comment]
Les deux points sont corrigés dans la branche Master, selon tes conseils avisés, et le build passe.
Merci pour ta participation sur MyDMAM.
